# Generated by Django 4.1.7 on 2023-03-21 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230315_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curs_name', models.CharField(max_length=200, verbose_name='названия курсы')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='curs_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.curs'),
            preserve_default=False,
        ),
    ]
