# Generated by Django 4.1.7 on 2023-03-22 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PostCountViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesId', models.CharField(db_index=True, max_length=150)),
                ('postId', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
